In [308]:
import pandas as pd
import numpy as np



In [309]:
PATH = 'C:/Users/sivagami.nambi/Documents/Housing/'
train_path = PATH + 'train.csv'
test_path = PATH +'test.csv'

In [310]:
train_data = pd.read_csv(train_path)
test_data = pd.read_csv(test_path)
train_data = train_data.dropna()
train_data = train_data.drop(labels ='ID', axis=1)
test_data_id = test_data.iloc[: ,0:1]
test_data = test_data.drop(labels ='ID', axis=1)
type(test_data_id)


pandas.core.frame.DataFrame

In [311]:
train_data_X = train_data.iloc[:, :-1]
train_data_y = train_data.iloc[:, -1]
# test_data_X = test_data.iloc[:, :-1]
# test_data_y = test_data.iloc[:, -1]

train_data_X = (train_data_X - train_data_X.mean()) / train_data_X.std()
test_data = (test_data - test_data.mean()) / test_data.std()

# print (train_data_X.head(5)) 
# print(train_data_y.head(5))
# print (test_data_X.head(5)) 
# print(test_data_y.head(5))

In [312]:
X = train_data_X.as_matrix()
y = train_data_y.as_matrix()
X_test = test_data.as_matrix()
test_data_id =test_data_id.as_matrix()
# X_test = test_data_X.as_matrix()
# y_test = test_data_y.as_matrix()
type(X)
print(y)

[24.  21.6 33.4 36.2 22.9 15.  18.9 21.7 20.4 18.2 19.9 23.1 20.2 13.6
 19.6 15.2 14.5 14.8 12.7 14.5 13.5 24.7 30.8 34.9 25.3 24.7 21.2 19.3
 20.  16.6 19.4 19.7 20.5 23.4 18.9 35.4 24.7 31.6 23.3 18.7 16.  25.
 33.  23.5 19.4 22.  17.4 24.2 22.8 23.4 24.1 21.4 20.  20.8 28.  23.9
 22.9 23.9 26.6 22.5 22.2 23.6 28.7 22.6 25.  20.6 21.4 27.5 26.5 18.6
 19.3 19.5 20.4 19.8 19.4 22.8 18.5 21.2 19.2 20.4 19.3 22.  20.3 20.5
 17.3 18.8 15.7 16.2 18.  19.6 18.4 15.6 17.4 17.1 13.3 17.8 14.4 13.4
 13.8 14.6 17.8 15.4 21.5 19.4 17.  13.1 24.3 23.3 27.  50.  50.  22.7
 25.  50.  23.8 22.3 17.4 19.1 23.1 23.6 22.6 29.4 23.2 24.6 29.9 37.2
 39.8 36.2 37.9 32.5 50.  32.  34.9 37.  30.5 36.4 31.1 29.1 30.3 32.9
 24.1 48.5 50.  22.6 24.4 24.4 19.3 28.1 23.7 23.3 21.7 27.5 30.1 44.8
 50.  37.6 31.6 31.5 24.3 41.7 48.3 29.  24.  25.1 22.  22.2 23.7 17.6
 24.3 24.5 26.2 24.4 24.8 42.8 33.8 43.1 48.8 31.  36.5 22.8 30.7 43.5
 25.2 24.4 35.2 32.4 35.1 35.4 46.  50.  32.2 22.  20.1 22.3 28.5 27.9
 23.9 2

In [313]:
def Linear_regression(X , y, alpha, iter):
    normalising_param = 2*X.shape[0]
    theta = np.ones(X.shape[1])                                       
    theta_req = np.ones(X.shape[1])                                 
    h_Theta = np.matmul(X, theta)
    loss = h_Theta - y
    j_Theta_min = np.matmul(loss.transpose(), loss)/normalising_param
    
    for i in range(iter):
        for feature in range(X.shape[1]):
            gradient = np.sum ( np.multiply(loss, X.T[feature]) )/X.shape[0]
            theta[feature] = theta[feature] - alpha*gradient
        h_Theta = np.matmul(X, theta)
        loss = h_Theta - y
        j_Theta = np.matmul(loss.transpose(), loss)/normalising_param
        print(j_Theta)
        if(j_Theta < j_Theta_min):
            j_Theta_min = j_Theta
            theta_req = theta
    
    return theta_req 
    
        
    

In [314]:
theta = Linear_regression(X, y, 0.01, 1000)

322.81293019794134
318.1637369077832
314.043109921761
310.38846048742374
307.14466716510213
304.2631835641093
301.7012527293715
299.4212154298836
297.38990112432805
295.5780917209735
293.96004943035086
292.5131010493645
291.21727193131835
290.0549637026823
289.010670497382
288.07072910447727
287.22309897547154
286.4571685220632
285.7635845618016
285.13410214476426
284.56145232511454
284.03922573260644
283.5617700555019
283.12409977211763
282.72181666697475
282.35103984253533
282.0083440915861
281.69070563100075
281.39545431705596
281.1202315676467
280.8629533093438
280.62177734876457
280.3950746395122
280.1814039791389
279.9794897262364
279.788202176754
279.60654028177856
279.4336164269985
279.2686430275089
279.1109207210663
278.95982796881844
278.8148118953675
278.675380220114
278.54109414953365
278.4115621156094
278.2864342593622
278.1653975705063
278.0481716048787
277.9345047106649
277.8241707026815
277.7169659312363
277.61270669847653
277.51122698076284
277.41237642056393
277.31601

270.6079884032501
270.6075302243805
270.6070734262499
270.60661800354205
270.6061639509657
270.6057112632541
270.60525993516484
270.6048099614792
270.60436133700335
270.6039140565666
270.6034681150228
270.60302350724874
270.60258022814526
270.60213827263647
270.60169763567006
270.6012583122161
270.6008202972685
270.6003835858438
270.59994817298144
270.5995140537434
270.5990812232142
270.5986496765011
270.59821940873326
270.59779041506215
270.5973626906616
270.596936230727
270.59651103047605
270.5960870851477
270.5956643900027
270.5952429403237
270.594822731414
270.5944037585987
270.5939860172237
270.5935695026565
270.5931542102849
270.592740135518
270.59232727378526
270.59191562053695
270.59150517124385
270.59109592139737
270.5906878665083
270.59028100210867
270.5898753237501
270.58947082700405
270.5890675074622
270.5886653607356
270.58826438245535
270.5878645682717
270.5874659138549
270.58706841489374
270.5866720670971
270.5862768661921
270.58588280792605
270.5854898880642
270.5850981

In [315]:
theta


array([-0.18442869,  0.80601679, -0.01037043,  0.94539275, -1.26119089,
        2.87347642, -0.22145428, -2.61581502,  1.62204284, -1.00717511,
       -1.72021251,  1.0636055 , -4.16875345])

In [317]:
y_predicted = np.matmul(X_test, theta)
y_predicted = y_predicted + 22.6
y_predicted

array([30.97882915, 25.7380507 , 18.83844876, 10.16869709, 18.56994101,
       17.28466336, 18.80439923, 15.90699692, 13.48737354, 15.83070651,
       20.11650192, 21.53159208,  8.31276408, 14.11684165, 23.32931964,
       21.78993741, 23.07215915, 28.72988803,  7.49117311, 27.94194491,
       21.16604965, 24.26692873, 21.40189969, 21.91050834, 21.49153632,
       22.68741929, 26.08232771, 27.03397358, 27.9677278 , 28.39253822,
       35.98170527, 35.59756819, 32.27855741, 21.41106332, 18.06432386,
       21.02953085, 20.25950258, 20.27109672, 19.95738182, 21.03183763,
       14.41285301, 20.86156203, 21.02424086, 17.87155529, 13.62773617,
       12.48979006,  8.6464386 , 16.21975111, 18.99123876, 21.49387677,
       21.63897826, 33.05366731, 41.53094373, 25.80714517, 21.08071856,
       23.6018938 , 32.15894904, 39.99057521, 35.86034014, 34.27223129,
       30.86366888, 37.2396331 , 17.081423  , 16.15829205, 22.03649827,
       22.64531756, 24.37184868, 27.63966655, 24.0249612 , 29.44

In [318]:
from sklearn.metrics import mean_squared_error
from math import sqrt

rms = sqrt(mean_squared_error(y_test, y_predicted))
print(rms)

17.508379100821326


In [319]:
from sklearn import linear_model

In [320]:
linear = linear_model.LinearRegression()

In [321]:
linear.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [322]:
y_pred = linear.predict(X_test)
print(y_pred)

[30.98658396 25.7524691  18.93812809 10.32019311 18.59038378 17.13393807
 18.8201514  15.76952248 13.45919023 15.68687079 19.82821841 21.21417075
  8.1664076  14.16229105 23.88909622 22.34540578 23.46894516 28.81972648
  8.00930837 28.28242116 21.77822285 24.74728938 21.21670776 22.28105747
 21.42537015 22.80545291 26.44492612 27.13994192 29.25814055 28.45148019
 35.64916568 35.22604961 32.08867267 21.32327978 18.11608341 20.74176636
 20.16532578 20.07892466 19.85243543 22.86350446 14.26874906 20.51540089
 20.67649588 17.51508352 13.33958903 11.8561408   8.19210185 15.77366612
 18.55535595 20.99820973 20.8025779  33.38891018 41.40962891 26.24006437
 22.10328026 24.33801293 32.21907176 40.66214654 35.80924879 34.21554845
 30.31287797 36.99108218 17.64639947 16.82580989 22.55038076 23.14030468
 24.8792274  28.42907474 24.91816526 30.18125316 33.44321309 35.9597778
 33.46130174 33.04781914 28.79241304 28.61286086 23.56236193 13.45032699
 20.33021574 26.26417348 24.31134619 21.95683126 37.

In [323]:
rms = sqrt(mean_squared_error(y_test, y_pred))
print(rms)

17.635282004204615


In [303]:
a = np.array([1,2])
a.reshape(1,2)
y_predicted = y_predicted_array.reshape(1, y_predicted_array.shape[0] )

In [325]:
test_data_id.T


array([[  3,   6,   8,   9,  10,  18,  20,  25,  26,  27,  29,  30,  33,
         34,  36,  37,  38,  42,  49,  53,  60,  63,  70,  72,  79,  80,
         83,  92,  93,  96,  98,  99, 100, 105, 106, 111, 113, 114, 116,
        126, 130, 131, 133, 136, 141, 144, 145, 147, 152, 153, 156, 158,
        163, 169, 185, 186, 189, 196, 197, 199, 200, 203, 208, 210, 211,
        213, 216, 218, 219, 220, 221, 229, 232, 238, 239, 240, 242, 246,
        248, 253, 255, 256, 257, 258, 259, 260, 268, 270, 271, 276, 277,
        278, 279, 281, 288, 290, 292, 295, 296, 299, 300, 301, 308, 314,
        315, 320, 322, 323, 324, 327, 330, 332, 333, 336, 338, 346, 347,
        351, 352, 354, 355, 356, 362, 364, 365, 370, 376, 379, 380, 381,
        382, 386, 389, 391, 394, 396, 398, 400, 403, 405, 406, 407, 410,
        411, 412, 413, 417, 421, 422, 423, 424, 427, 431, 436, 437, 439,
        447, 450, 451, 455, 457, 471, 474, 476, 483, 486, 490, 495, 496,
        497, 499, 501, 505]], dtype=int64)

In [328]:
df = pd.DataFrame(hello)
df.to_csv("file_path1.csv")